#!/bin/bash
export AMANDROID_DIST=true
export AMANDROID_HOME=$( cd "$( dirname "$0" )" &> /dev/null && pwd )
if [ ! -d $AMANDROID_HOME/platform/java ]; then
  echo "Did not find java. Run setup first."
  exit -1
fi
if [ ! -d $AMANDROID_HOME/platform/scala ]; then
  echo "Did not find scala. Run setup first."
  exit -1
fi

export JAVA_HOME=$AMANDROID_HOME/platform/java
export SCALA_HOME=$AMANDROID_HOME/platform/scala
export PATH=$SCALA_HOME/bin:$JAVA_HOME/bin:$PATH
scala -target:jvm-1.8 -nocompdaemon -savecompiled $SCALA_OPTIONS $0 $AMANDROID_HOME "$@"
code=$?
exit $code
!#
AmandroidMain.main(args)